In [23]:
#pip install mygene pandas
import mygene
import pandas as pd

In [2]:
gene_list = ["TP53", "BRCA1", "APOE", "EGFR"]

In [3]:
mg = mygene.MyGeneInfo()

In [4]:
print("Fetching biological functions from MyGene.info...")
results = mg.querymany(
    gene_list,
    scopes="symbol",
    fields="go.BP",  # BP stands for Biological Process
    species="human",
    returnall=False
)

Fetching biological functions from MyGene.info...

In [5]:
parsed_data = []

for entry in results:
    gene_name = entry.get("query")
    go_data = entry.get("go", {})
    
    # Check if Biological Process data exists for this gene
    if "BP" in go_data:
        bp_list = go_data["BP"]
        
        # Handle cases where there is only one GO term (dictionary instead of a list)
        if isinstance(bp_list, dict):
            bp_list = [bp_list]
            
        for term in bp_list:
            parsed_data.append({
                "Gene Name": gene_name,
                "GO ID": term.get("id"),
                "Biological Function": term.get("term")
            })
    else:
        # Keep track of genes that didn't return any functions
        parsed_data.append({
            "Gene Name": gene_name,
            "GO ID": "None Found",
            "Biological Function": "None Found"
        })

# 5. Convert to a Pandas DataFrame and save to CSV
df = pd.DataFrame(parsed_data)
df.to_csv("gene_biological_functions.csv", index=False)

print("\nSuccess! Results saved to 'gene_biological_functions.csv'")
print(df.head(10))

Success! Results saved to 'gene_biological_functions.csv'
  Gene Name       GO ID                                Biological Function
0      TP53  GO:0000122  negative regulation of transcription by RNA po...
1      TP53  GO:0000122  negative regulation of transcription by RNA po...
2      TP53  GO:0002244      hematopoietic progenitor cell differentiation
3      TP53  GO:0006289                         nucleotide-excision repair
4      TP53  GO:0006355          regulation of DNA-templated transcription
5      TP53  GO:0006355          regulation of DNA-templated transcription
6      TP53  GO:0006355          regulation of DNA-templated transcription
7      TP53  GO:0006357   regulation of transcription by RNA polymerase II
8      TP53  GO:0006914                                          autophagy
9      TP53  GO:0006915                                  apoptotic process

In [6]:
import mygene
import pandas as pd

# 1. Read gene names from your .txt file
txt_file_path = "gene_names.txt"  # Replace with your actual file path

with open(txt_file_path, "r") as f:
    gene_list = [line.strip() for line in f if line.strip()]

print(f"Loaded {len(gene_list)} genes from {txt_file_path}.")

# 2. Initialize the MyGene client
mg = mygene.MyGeneInfo()

# 3. Query the database for GO Biological Process (BP) annotations
print("Fetching data from MyGene.info...")
results = mg.querymany(
    gene_list,
    scopes="symbol",
    fields="go.BP",
    species="human",  # Change to your organism if not human
    returnall=False
)

# 4. Parse and club GO IDs and Functions together per gene
parsed_data = []

for entry in results:
    gene_name = entry.get("query")
    go_data = entry.get("go", {})
    
    # Check if Biological Process (BP) data exists
    if "BP" in go_data:
        bp_list = go_data["BP"]
        
        # Ensure bp_list is always treated as a list of dictionaries
        if isinstance(bp_list, dict):
            bp_list = [bp_list]
            
        # Extract IDs and Terms
        go_ids = [term.get("id") for term in bp_list if term.get("id")]
        functions = [term.get("term") for term in bp_list if term.get("term")]
        
        # Club them into comma-separated strings
        combined_ids = ", ".join(go_ids)
        combined_functions = ", ".join(functions)
        
    else:
        combined_ids = "None Found"
        combined_functions = "None Found"
        
    parsed_data.append({
        "Gene Name": gene_name,
        "GO IDs": combined_ids,
        "Biological Functions": combined_functions
    })

# 5. Save the combined results to a CSV file
df = pd.DataFrame(parsed_data)
output_file = "combined_gene_go_data.csv"
df.to_csv(output_file, index=False)

print(f"\nSuccess! Results saved to '{output_file}'")
print(df.head())

Loaded 20360 genes from gene_names.txt.
Fetching data from MyGene.info...

500 input query terms found dup hits:	[('ADAMTSL4-AS1', 2), ('ADGRE4P', 2), ('AGAP11', 2), ('AHSA2P', 2), ('AK4P3', 2), ('ANKRD19P', 2), (
295 input query terms found no hit:	['AATK', 'ACOT7L', 'ADAL', 'ADGRF2', 'AKAP2', 'ARMT1', 'ATP6V1FNB', 'B3GNTL1', 'BAP18', 'BARGIN', 'B

Success! Results saved to 'combined_gene_go_data.csv'
  Gene Name                                             GO IDs  \
0      A1BG                                         GO:0060396
1      A1CF  GO:0016554, GO:0016554, GO:0016556, GO:0050821...
2       A2M                                         GO:0001869
3     A2ML1                                         GO:0052548
4   A3GALT2                             GO:0005975, GO:0006688

                                Biological Functions
0          growth hormone receptor signaling pathway
1  cytidine to uridine editing, cytidine to uridi...
2  negative regulation of complement activation, ...
3               regulation of endopeptidase activity
4  carbohydrate metabolic process, glycosphingoli...

In [5]:
with open("interactions.tsv", "r", encoding="utf-8") as f:
    for i in range(10):
        print(i + 1, repr(f.readline()))

1 '# Data version: Dec-2023\n'
2 '# DGIdb version: v.5.0.11\n'
3 'gene_claim_name\tgene_concept_id\tgene_name\tdrug_claim_name\tdrug_concept_id\tdrug_name\tdrug_is_approved\tdrug_is_immunotherapy\tdrug_is_antineoplastic\tinteraction_source_db_name\tinteraction_source_db_version\tinteraction_types\tinteraction_score\tdrug_specificity_score\tgene_specificity_score\tevidence_score\n'
4 'IUPHAR.RECEPTOR:2158\thgnc:8986\tPIM1\tIUPHAR.LIGAND:8115\tiuphar.ligand:8115\tCOMPOUND 2 [PMID: 22560567]\tfalse\tfalse\tfalse\tGuideToPharmacology\t2026.2\tinhibitor\t0.2496791957230317\t0.8434374850471315\t0.29602572822463497\t1\n'
5 'IUPHAR.RECEPTOR:2158\thgnc:8986\tPIM1\tIUPHAR.LIGAND:8784\tiuphar.ligand:8784\tSGI-1776\tfalse\tfalse\tfalse\tGuideToPharmacology\t2026.2\tinhibitor\t0.3329055942973757\t0.5622916566980877\t0.29602572822463497\t2\n'
6 'IUPHAR.RECEPTOR:2158\thgnc:8986\tPIM1\tIUPHAR.LIGAND:10195\tiuphar.ligand:10195\tCOMPOUND 28 [PMID: 30624936]\tfalse\tfalse\tfalse\tGuideToPharmacology\t2026.2\tinhibitor\t0.4993583914460635\t1.686874970094263\t0.29602572822463497\t1\n'
7 'IUPHAR.RECEPTOR:2158\thgnc:8986\tPIM1\tIUPHAR.LIGAND:8214\tiuphar.ligand:8214\tCOMPOUND 14K [PMID: 21982499]\tfalse\tfalse\tfalse\tGuideToPharmacology\t2026.2\tinhibitor\t0.1997433565784254\t0.6747499880377051\t0.29602572822463497\t1\n'
8 'IUPHAR.RECEPTOR:2158\thgnc:8986\tPIM1\tIUPHAR.LIGAND:5263\tncit:C66524\tRUBOXISTAURIN\tfalse\tfalse\tfalse\tGuideToPharmacology\t2026.2\tinhibitor\t0.1426738261274467\t0.4819642771697894\t0.29602572822463497\t1\n'
9 'IUPHAR.RECEPTOR:2158\thgnc:8986\tPIM1\tIUPHAR.LIGAND:9923\tncit:C141430\tVORUCICLIB\tfalse\tfalse\ttrue\tGuideToPharmacology\t2026.2\tinhibitor\t0.06658111885947514\t0.22491666267923505\t0.29602572822463497\t1\n'
10 'IUPHAR.RECEPTOR:2158\thgnc:8986\tPIM1\tIUPHAR.LIGAND:13204\tiuphar.ligand:13204\tDAPOLSERTIB\tfalse\tfalse\tfalse\tGuideToPharmacology\t2026.2\tinhibitor\t0.3329055942973757\t1.1245833133961753\t0.29602572822463497\t1\n'

In [7]:
df_gene_drug = pd.read_csv(
    "interactions.tsv",
    sep="\t",
    comment="#"
)
df_gene_drug

,gene_claim_name,gene_concept_id,gene_name,drug_claim_name,drug_concept_id,drug_name,drug_is_approved,drug_is_immunotherapy,drug_is_antineoplastic,interaction_source_db_name,interaction_source_db_version,interaction_types,interaction_score,drug_specificity_score,gene_specificity_score,evidence_score
0,IUPHAR.RECEPTOR:2158,hgnc:8986,PIM1,IUPHAR.LIGAND:8115,iuphar.ligand:8115,COMPOUND 2 [PMID: 22560567],False,False,False,GuideToPharmacology,2026.2,inhibitor,0.249679,0.843437,0.296026,1.0
1,IUPHAR.RECEPTOR:2158,hgnc:8986,PIM1,IUPHAR.LIGAND:8784,iuphar.ligand:8784,SGI-1776,False,False,False,GuideToPharmacology,2026.2,inhibitor,0.332906,0.562292,0.296026,2.0
2,IUPHAR.RECEPTOR:2158,hgnc:8986,PIM1,IUPHAR.LIGAND:10195,iuphar.ligand:10195,COMPOUND 28 [PMID: 30624936],False,False,False,GuideToPharmacology,2026.2,inhibitor,0.499358,1.686875,0.296026,1.0
3,IUPHAR.RECEPTOR:2158,hgnc:8986,PIM1,IUPHAR.LIGAND:8214,iuphar.ligand:8214,COMPOUND 14K [PMID: 21982499],False,False,False,GuideToPharmacology,2026.2,inhibitor,0.199743,0.674750,0.296026,1.0
4,IUPHAR.RECEPTOR:2158,hgnc:8986,PIM1,IUPHAR.LIGAND:5263,ncit:C66524,RUBOXISTAURIN,False,False,False,GuideToPharmacology,2026.2,inhibitor,0.142674,0.481964,0.296026,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
101055,PRKG2,hgnc:9416,PRKG2,GSK-269962A,iuphar.ligand:8037,GSK269962A,False,False,False,DTC,2020-09-02,NaN,0.287674,0.073342,3.922341,1.0
101056,IUPHAR.RECEPTOR:523,hgnc:6275,KCNK13,IUPHAR.LIGAND:13373,iuphar.ligand:13373,CVN293,False,False,False,GuideToPharmacology,2026.2,inhibitor,26.465995,3.373750,7.844682,1.0
101057,IUPHAR.RECEPTOR:523,hgnc:6275,KCNK13,IUPHAR.LIGAND:2401,rxcui:5095,HALOTHANE,True,False,False,GuideToPharmacology,2026.2,inhibitor,0.853742,0.108831,7.844682,1.0
101058,WEE1,hgnc:12761,WEE1,AZENOSERTIB,chembl:CHEMBL5095036,AZENOSERTIB,False,False,False,ChEMBL,37,inhibitor,3.308249,3.373750,0.980585,1.0
101059,WEE1,hgnc:12761,WEE1,ADAVOSERTIB,iuphar.ligand:7702,ADAVOSERTIB,False,False,True,ChEMBL,37,inhibitor,0.551375,0.140573,0.980585,4.0

In [8]:
druggable_genes = (
    df_gene_drug["gene_name"]
    .dropna()
    .drop_duplicates()
    .sort_values()
    .reset_index(drop=True)
)

print("Number of druggable genes:", len(druggable_genes))
print(druggable_genes)

Number of druggable genes: 4652
0           A2M
1         AADAC
2         AADAT
3          AAK1
4         AANAT
         ...
4647     ZNF816
4648      ZRSR2
4649    ZSCAN25
4650       ZUP1
4651        mCR
Name: gene_name, Length: 4652, dtype: object

In [9]:
approved_druggable_genes = (
    df_gene_drug.loc[
        df_gene_drug["drug_is_approved"] == True,
        "gene_name"
    ]
    .dropna()
    .drop_duplicates()
    .sort_values()
    .reset_index(drop=True)
)

print("Approved-drug-targeted genes:", len(approved_druggable_genes))

Approved-drug-targeted genes: 3338

In [10]:
approved_druggable_genes

0           A2M
1         AADAC
2          AAK1
3         AANAT
4          ABAT
         ...
3333     ZNF697
3334     ZNF703
3335     ZNF816
3336    ZSCAN25
3337        mCR
Name: gene_name, Length: 3338, dtype: object

In [11]:
df_gene_drug["drug_is_approved"].value_counts()

drug_is_approved
False    52250
True     38170
Name: count, dtype: int64

In [12]:
fda_df = df_gene_drug[
    df_gene_drug["drug_is_approved"].astype(str).str.lower() == "true"
].copy()

In [13]:
fda_druggable_genes = (
    fda_df["gene_name"]
    .dropna()
    .drop_duplicates()
    .sort_values()
    .reset_index(drop=True)
)

print("FDA-approved druggable genes:", len(fda_druggable_genes))
print(fda_druggable_genes)

FDA-approved druggable genes: 3338
0           A2M
1         AADAC
2          AAK1
3         AANAT
4          ABAT
         ...
3333     ZNF697
3334     ZNF703
3335     ZNF816
3336    ZSCAN25
3337        mCR
Name: gene_name, Length: 3338, dtype: object

In [14]:
fda_gene_drug = (
    fda_df[
        [
            "gene_name",
            "drug_name",
            "drug_is_approved",
            "interaction_types",
            "interaction_score",
            "interaction_source_db_name"
        ]
    ]
    .drop_duplicates()
    .sort_values(["gene_name", "drug_name"])
)

display(fda_gene_drug.head())

,gene_name,drug_name,drug_is_approved,interaction_types,interaction_score,interaction_source_db_name
74930,A2M,ALPROSTADIL,True,NaN,1.260285,NCI
66341,A2M,TECHNETIUM TC 99M SUCCIMER,True,binder,13.232997,ChEMBL
74929,A2M,THROMBIN ALFA,True,NaN,1.260285,NCI
97418,AADAC,DOLUTEGRAVIR SODIUM,True,NaN,17.643996,PharmGKB
97419,AADAC,ESLICARBAZEPINE ACETATE,True,NaN,4.811999,PharmGKB

In [15]:
gene_drug_summary = (
    fda_df
    .groupby("gene_name")["drug_name"]
    .nunique()
    .sort_values(ascending=False)
    .reset_index(name="FDA_approved_drug_count")
)

display(gene_drug_summary.head(20))

   gene_name  FDA_approved_drug_count
0     CYP3A4                      353
1     CYP2D6                      330
2         AR                      311
3     CYP1A2                      243
4     CYP2C9                      215
5    CYP2C19                      214
6      EHMT2                      192
7     NFE2L2                      180
8       TP53                      154
9      ABCB1                      131
10      HRH1                      127
11      DRD2                      124
12       VDR                      118
13      ESR1                      107
14     KCNH2                       98
15     NR3C1                       92
16     ADRB2                       92
17      IDH1                       92
18      GMNN                       91
19    ADRA1A                       90

In [16]:
# Keep FDA-approved drug interactions
fda_df = df_gene_drug[
    df_gene_drug["drug_is_approved"].astype(str).str.lower() == "true"
].copy()

# Gene + FDA-approved drug
fda_gene_drugs = (
    fda_df[["gene_name", "drug_name"]]
    .dropna()
    .drop_duplicates()
    .sort_values(["gene_name", "drug_name"])
)

print(fda_gene_drugs)

      gene_name                   drug_name
74930       A2M                 ALPROSTADIL
66341       A2M  TECHNETIUM TC 99M SUCCIMER
74929       A2M               THROMBIN ALFA
97418     AADAC         DOLUTEGRAVIR SODIUM
97419     AADAC     ESLICARBAZEPINE ACETATE
...         ...                         ...
52399   ZSCAN25        ANHYDROUS TACROLIMUS
52397   ZSCAN25                    APIXABAN
52398   ZSCAN25                   LOPINAVIR
52400   ZSCAN25                  PERAMPANEL
7101        mCR               BREMELANOTIDE

[24006 rows x 2 columns]

In [17]:
druggable_genes = (
    fda_df["gene_name"]
    .dropna()
    .drop_duplicates()
    .sort_values()
)

druggable_genes.to_csv(
    "druggable_genes.txt",
    index=False,
    header=False
)

In [18]:
print("Number of druggable genes:", len(druggable_genes))

Number of druggable genes: 3338

In [58]:
import pandas as pd

panther_df = pd.read_csv(
    "pantherGeneList_2.txt",
    sep="\t"
)

panther_df.head()

,HUMAN|HGNC=17399|UniProtKB=A7KAX9,HUMAN|HGNC=17399|UniProtKB=A7KAX9.1,Rho GTPase-activating protein 32;ARHGAP32;PTN002496528;orthologs,Homo sapiens,small GTPase-mediated signal transduction(GO:0007264),Gonadotropin-releasing hormone receptor pathway->RICS;;Gonadotropin-releasing hormone receptor pathway->RICS;;Gonadotropin-releasing hormone receptor pathway->RICS;;;;
0,HUMAN|HGNC=10059|UniProtKB=O00635,HUMAN|HGNC=10059|UniProtKB=O00635,E3 ubiquitin-protein ligase TRIM38;TRIM38;PTN0...,Homo sapiens,innate immune response(GO:0045087);regulation ...,NaN
1,HUMAN|HGNC=18234|UniProtKB=Q96EN8,HUMAN|HGNC=18234|UniProtKB=Q96EN8,Molybdenum cofactor sulfurase;MOCOS;PTN0024943...,Homo sapiens,NaN,NaN
2,HUMAN|HGNC=1336|UniProtKB=Q9NYF3,HUMAN|HGNC=1336|UniProtKB=Q9NYF3,Protein FAM53C;FAM53C;PTN002523895;orthologs,Homo sapiens,protein import into nucleus(GO:0006606),NaN
3,HUMAN|HGNC=8155|UniProtKB=P41146,HUMAN|HGNC=8155|UniProtKB=P41146,Nociceptin receptor;OPRL1;PTN002517290;orthologs,Homo sapiens,neuropeptide signaling pathway(GO:0007218);sen...,Heterotrimeric G-protein signaling pathway-Gi ...
4,HUMAN|HGNC=28078|UniProtKB=A1A4V9,HUMAN|HGNC=28078|UniProtKB=A1A4V9,Cilia- and flagella-associated protein 119;CFA...,Homo sapiens,NaN,NaN

In [60]:
panther_df = pd.read_csv(
    "pantherGeneList_2.txt",
    sep="\t",
    header=None
)
print(panther_df.head().to_string())
panther_df.columns = [
    "gene_identifier",
    "gene_identifier_2",
    "gene_description",
    "organism",
    "go_annotations",
    "pathways"
]
panther_df.head()

                                   0                                  1                                                                 2             3                                                                                                                4                                                                                                                                                                                                                                  5
0  HUMAN|HGNC=17399|UniProtKB=A7KAX9  HUMAN|HGNC=17399|UniProtKB=A7KAX9  Rho GTPase-activating protein 32;ARHGAP32;PTN002496528;orthologs  Homo sapiens                                                            small GTPase-mediated signal transduction(GO:0007264)                                                            Gonadotropin-releasing hormone receptor pathway->RICS;;Gonadotropin-releasing hormone receptor pathway->RICS;;Gonadotropin-releasing hormone receptor pathway->RICS;;;;
1  HUMAN|HGNC=10059|UniProtKB=O00635  HUMAN|HGNC=10059|UniProtKB=O00635  E3 ubiquitin-protein ligase TRIM38;TRIM38;PTN002515823;orthologs  Homo sapiens  innate immune response(GO:0045087);regulation of gene expression(GO:0010468);protein ubiquitination(GO:0016567)                                                                                                                                                                                                                                NaN
2  HUMAN|HGNC=18234|UniProtKB=Q96EN8  HUMAN|HGNC=18234|UniProtKB=Q96EN8        Molybdenum cofactor sulfurase;MOCOS;PTN002494397;orthologs  Homo sapiens                                                                                                              NaN                                                                                                                                                                                                                                NaN
3   HUMAN|HGNC=1336|UniProtKB=Q9NYF3   HUMAN|HGNC=1336|UniProtKB=Q9NYF3                      Protein FAM53C;FAM53C;PTN002523895;orthologs  Homo sapiens                                                                          protein import into nucleus(GO:0006606)                                                                                                                                                                                                                                NaN
4   HUMAN|HGNC=8155|UniProtKB=P41146   HUMAN|HGNC=8155|UniProtKB=P41146                  Nociceptin receptor;OPRL1;PTN002517290;orthologs  Homo sapiens                                        neuropeptide signaling pathway(GO:0007218);sensory perception(GO:0007600)  Heterotrimeric G-protein signaling pathway-Gi alpha and Gs alpha mediated pathway->Gi protein coupled receptor;;Heterotrimeric G-protein signaling pathway-Gq alpha and Go alpha mediated pathway->Go-protein coupled receptor;;;

,gene_identifier,gene_identifier_2,gene_description,organism,go_annotations,pathways
0,HUMAN|HGNC=17399|UniProtKB=A7KAX9,HUMAN|HGNC=17399|UniProtKB=A7KAX9,Rho GTPase-activating protein 32;ARHGAP32;PTN0...,Homo sapiens,small GTPase-mediated signal transduction(GO:0...,Gonadotropin-releasing hormone receptor pathwa...
1,HUMAN|HGNC=10059|UniProtKB=O00635,HUMAN|HGNC=10059|UniProtKB=O00635,E3 ubiquitin-protein ligase TRIM38;TRIM38;PTN0...,Homo sapiens,innate immune response(GO:0045087);regulation ...,NaN
2,HUMAN|HGNC=18234|UniProtKB=Q96EN8,HUMAN|HGNC=18234|UniProtKB=Q96EN8,Molybdenum cofactor sulfurase;MOCOS;PTN0024943...,Homo sapiens,NaN,NaN
3,HUMAN|HGNC=1336|UniProtKB=Q9NYF3,HUMAN|HGNC=1336|UniProtKB=Q9NYF3,Protein FAM53C;FAM53C;PTN002523895;orthologs,Homo sapiens,protein import into nucleus(GO:0006606),NaN
4,HUMAN|HGNC=8155|UniProtKB=P41146,HUMAN|HGNC=8155|UniProtKB=P41146,Nociceptin receptor;OPRL1;PTN002517290;orthologs,Homo sapiens,neuropeptide signaling pathway(GO:0007218);sen...,Heterotrimeric G-protein signaling pathway-Gi ...

In [61]:
panther_df["gene_name"] = (
    panther_df["gene_description"]
    .str.split(";")
    .str[1]
    .str.strip()
    .str.upper()
)

In [62]:
panther_df[
    ["gene_description", "gene_name"]
].head()

                                    gene_description gene_name
0  Rho GTPase-activating protein 32;ARHGAP32;PTN0...  ARHGAP32
1  E3 ubiquitin-protein ligase TRIM38;TRIM38;PTN0...    TRIM38
2  Molybdenum cofactor sulfurase;MOCOS;PTN0024943...     MOCOS
3       Protein FAM53C;FAM53C;PTN002523895;orthologs    FAM53C
4   Nociceptin receptor;OPRL1;PTN002517290;orthologs     OPRL1

In [63]:
go_df = panther_df[
    ["gene_name", "go_annotations"]
].copy()

In [64]:
go_df["go_annotation"] = (
    go_df["go_annotations"]
    .str.split(";")
)

go_df = go_df.explode("go_annotation")

In [65]:
go_df["go_annotation"] = (
    go_df["go_annotations"]
    .str.split(";")
)

go_df = go_df.explode("go_annotation")

In [66]:
go_df["go_annotation"] = (
    go_df["go_annotation"]
    .str.strip()
)

In [67]:
go_df = go_df[
    go_df["go_annotation"].notna()
    & go_df["go_annotation"].ne("")
]

In [68]:
go_df["go_id"] = (
    go_df["go_annotation"]
    .str.extract(r"(GO:\d+)", expand=False)
)

In [69]:
go_df["biological_function"] = (
    go_df["go_annotation"]
    .str.replace(r"\s*\(GO:\d+\)", "", regex=True)
    .str.strip()
)

In [70]:
go_df.head()

,gene_name,go_annotations,go_annotation,go_id,biological_function
0,ARHGAP32,small GTPase-mediated signal transduction(GO:0...,small GTPase-mediated signal transduction(GO:0...,GO:0007264,small GTPase-mediated signal transduction
1,TRIM38,innate immune response(GO:0045087);regulation ...,innate immune response(GO:0045087),GO:0045087,innate immune response
1,TRIM38,innate immune response(GO:0045087);regulation ...,regulation of gene expression(GO:0010468),GO:0010468,regulation of gene expression
1,TRIM38,innate immune response(GO:0045087);regulation ...,protein ubiquitination(GO:0016567),GO:0016567,protein ubiquitination
1,TRIM38,innate immune response(GO:0045087);regulation ...,innate immune response(GO:0045087),GO:0045087,innate immune response

In [71]:
go_df = (
    go_df[
        [
            "gene_name",
            "go_id",
            "biological_function"
        ]
    ]
    .dropna(subset=["gene_name", "biological_function"])
    .drop_duplicates()
    .sort_values(["gene_name", "biological_function"])
)

In [72]:
print("Number of genes:", go_df["gene_name"].nunique())
print("Number of GO annotations:", len(go_df))

Number of genes: 12407
Number of GO annotations: 26416

In [73]:
go_df.groupby("gene_name").size().describe()

count    12407.000000
mean         2.129121
std          1.667925
min          1.000000
25%          1.000000
50%          2.000000
75%          3.000000
max         30.000000
dtype: float64

In [74]:
panther_df

,gene_identifier,gene_identifier_2,gene_description,organism,go_annotations,pathways,gene_name
0,HUMAN|HGNC=17399|UniProtKB=A7KAX9,HUMAN|HGNC=17399|UniProtKB=A7KAX9,Rho GTPase-activating protein 32;ARHGAP32;PTN0...,Homo sapiens,small GTPase-mediated signal transduction(GO:0...,Gonadotropin-releasing hormone receptor pathwa...,ARHGAP32
1,HUMAN|HGNC=10059|UniProtKB=O00635,HUMAN|HGNC=10059|UniProtKB=O00635,E3 ubiquitin-protein ligase TRIM38;TRIM38;PTN0...,Homo sapiens,innate immune response(GO:0045087);regulation ...,NaN,TRIM38
2,HUMAN|HGNC=18234|UniProtKB=Q96EN8,HUMAN|HGNC=18234|UniProtKB=Q96EN8,Molybdenum cofactor sulfurase;MOCOS;PTN0024943...,Homo sapiens,NaN,NaN,MOCOS
3,HUMAN|HGNC=1336|UniProtKB=Q9NYF3,HUMAN|HGNC=1336|UniProtKB=Q9NYF3,Protein FAM53C;FAM53C;PTN002523895;orthologs,Homo sapiens,protein import into nucleus(GO:0006606),NaN,FAM53C
4,HUMAN|HGNC=8155|UniProtKB=P41146,HUMAN|HGNC=8155|UniProtKB=P41146,Nociceptin receptor;OPRL1;PTN002517290;orthologs,Homo sapiens,neuropeptide signaling pathway(GO:0007218);sen...,Heterotrimeric G-protein signaling pathway-Gi ...,OPRL1
...,...,...,...,...,...,...,...
20575,HUMAN|HGNC=4112|UniProtKB=Q96GT9,HUMAN|HGNC=4112|UniProtKB=Q96GT9,X antigen family member 2;XAGE2;PTN001796625;o...,Homo sapiens,NaN,NaN,XAGE2
20576,HUMAN|HGNC=30087|UniProtKB=Q5T7W7,HUMAN|HGNC=30087|UniProtKB=Q5T7W7,Thiosulfate sulfurtransferase_rhodanese-like d...,Homo sapiens,NaN,NaN,TSTD2
20577,HUMAN|HGNC=17142|UniProtKB=Q96CV9,HUMAN|HGNC=17142|UniProtKB=Q96CV9,Optineurin;OPTN;PTN002527036;orthologs,Homo sapiens,protein localization to Golgi apparatus(GO:003...,Huntington disease->FIP-2;;,OPTN
20578,HUMAN|HGNC=15703|UniProtKB=Q9HBH0,HUMAN|HGNC=15703|UniProtKB=Q9HBH0,Rho-related GTP-binding protein RhoF;RHOF;PTN0...,Homo sapiens,regulation of actin cytoskeleton organization(...,NaN,RHOF
20579,HUMAN|HGNC=32166|UniProtKB=A6NFQ7,HUMAN|HGNC=32166|UniProtKB=A6NFQ7,Divergent paired-related homeobox;DPRX;PTN0025...,Homo sapiens,regulation of transcription by RNA polymerase ...,NaN,DPRX

In [75]:
print("Total rows in original PANTHER file:", len(panther_df))
print("Unique genes in original PANTHER file:", panther_df["gene_name"].nunique())

Total rows in original PANTHER file: 20580
Unique genes in original PANTHER file: 20361

In [76]:
# Total rows
print("Total rows:", len(panther_df))

# Unique genes
print("Unique genes:", panther_df["gene_name"].nunique())

# Number of repeated gene rows
print("Extra rows beyond unique genes:",
      len(panther_df) - panther_df["gene_name"].nunique())

# Unique gene-GO pairs
print(
    "Unique gene-GO pairs:",
    go_df[["gene_name", "go_id"]].drop_duplicates().shape[0]
)

# Duplicate gene-GO pairs
duplicate_gene_go = go_df[
    go_df.duplicated(subset=["gene_name", "go_id"], keep=False)
]

print("Rows involved in duplicate gene-GO pairs:",
      len(duplicate_gene_go))

Total rows: 20580
Unique genes: 20361
Extra rows beyond unique genes: 219
Unique gene-GO pairs: 26416
Rows involved in duplicate gene-GO pairs: 0

In [77]:
print("Original PANTHER rows:", len(panther_df))
print("Original unique genes:", panther_df["gene_name"].nunique())

print("Processed GO rows:", len(go_df))
print("Processed unique genes:", go_df["gene_name"].nunique())
print("Processed unique GO terms:", go_df["go_id"].nunique())

print(go_df.head())

Original PANTHER rows: 20580
Original unique genes: 20361
Processed GO rows: 26416
Processed unique genes: 12407
Processed unique GO terms: 1799
      gene_name       go_id                           biological_function
19616      A1BG  GO:0002764  immune response-regulating signaling pathway
19690   A3GALT2  GO:0070085                                 glycosylation
19690   A3GALT2  GO:0030258                            lipid modification
10638    A4GALT  GO:0006688        glycosphingolipid biosynthetic process
8912      A4GNT  GO:0006688        glycosphingolipid biosynthetic process

In [78]:
genes_with_go = go_df["gene_name"].nunique()

print("Genes with at least one GO annotation:", genes_with_go)
print(
    "Percentage of genes with GO annotations:",
    round(genes_with_go / panther_df["gene_name"].nunique() * 100, 2),
    "%"
)

Genes with at least one GO annotation: 12407
Percentage of genes with GO annotations: 60.94 %

In [79]:
go_df = (
    go_df[["gene_name", "go_id", "biological_function"]]
    .dropna(subset=["gene_name", "biological_function"])
    .drop_duplicates()
    .sort_values(["gene_name", "biological_function"])
    .reset_index(drop=True)
)

In [80]:
print("Processed GO rows:", len(go_df))
print("Processed unique genes:", go_df["gene_name"].nunique())
print("Processed unique GO terms:", go_df["go_id"].nunique())

print(go_df.head())

Processed GO rows: 26416
Processed unique genes: 12407
Processed unique GO terms: 1799
  gene_name       go_id                           biological_function
0      A1BG  GO:0002764  immune response-regulating signaling pathway
1   A3GALT2  GO:0070085                                 glycosylation
2   A3GALT2  GO:0030258                            lipid modification
3    A4GALT  GO:0006688        glycosphingolipid biosynthetic process
4     A4GNT  GO:0006688        glycosphingolipid biosynthetic process

In [81]:
go_df

      gene_name       go_id                                biological_function
0          A1BG  GO:0002764       immune response-regulating signaling pathway
1       A3GALT2  GO:0070085                                      glycosylation
2       A3GALT2  GO:0030258                                 lipid modification
3        A4GALT  GO:0006688             glycosphingolipid biosynthetic process
4         A4GNT  GO:0006688             glycosphingolipid biosynthetic process
...         ...         ...                                                ...
26411      ZXDA  GO:0006357   regulation of transcription by RNA polymerase II
26412      ZXDB  GO:0006357   regulation of transcription by RNA polymerase II
26413      ZXDC  GO:0006357   regulation of transcription by RNA polymerase II
26414       ZYX  GO:0007229                integrin-mediated signaling pathway
26415       ZYX  GO:0007179  transforming growth factor beta receptor signa...

[26416 rows x 3 columns]

In [82]:
go_df_combined = (
    go_df.groupby("gene_name", as_index=False)
    .agg({
        "go_id": lambda x: "; ".join(sorted(set(x))),
        "biological_function": lambda x: "; ".join(sorted(set(x)))
    })
)

print(go_df_combined.head())

  gene_name                   go_id  \
0      A1BG              GO:0002764
1   A3GALT2  GO:0030258; GO:0070085
2    A4GALT              GO:0006688
3     A4GNT  GO:0006493; GO:0006688
4      AAAS              GO:0006913

                                 biological_function
0       immune response-regulating signaling pathway
1                  glycosylation; lipid modification
2             glycosphingolipid biosynthetic process
3  glycosphingolipid biosynthetic process; protei...
4                        nucleocytoplasmic transport

In [84]:
all_genes = set(panther_df["gene_name"].dropna().str.upper())
go_genes = set(go_df_combined["gene_name"].dropna().str.upper())

genes_without_go = all_genes - go_genes

print("All genes:", len(all_genes))
print("Genes with GO:", len(go_genes))
print("Genes without GO:", len(genes_without_go))

print(sorted(genes_without_go)[:50])

All genes: 20361
Genes with GO: 12407
Genes without GO: 7954
['A1CF', 'A2M', 'A2ML1', 'AACS', 'AADAC', 'AADACL2', 'AADACL3', 'AADACL4', 'AAGAB', 'AAMDC', 'AAMP', 'AANAT', 'AARD', 'AARSD1', 'AASDH', 'AASS', 'AATF', 'ABCB10', 'ABCD4', 'ABCF1', 'ABCF2', 'ABCF3', 'ABHD10', 'ABHD11', 'ABHD13', 'ABHD14A', 'ABHD18', 'ABITRAM', 'ABR', 'ABTB1', 'ABTB2', 'ABTB3', 'ACAD8', 'ACAD9', 'ACADS', 'ACADSB', 'ACADVL', 'ACAP1', 'ACAP2', 'ACAP3', 'ACAT2', 'ACBD3', 'ACBD6', 'ACD', 'ACE2', 'ACER3', 'ACHE', 'ACKR1', 'ACOT13', 'ACP1']

In [85]:
no_go_df = panther_df[
    panther_df["gene_name"].isin(genes_without_go)
]

print(no_go_df[[
    "gene_name",
    "gene_description",
    "organism",
    "go_annotations",
    "pathways"
]].head(30).to_string())

   gene_name                                                                          gene_description      organism go_annotations                                                                                                                                                                                                                                                                                                                                                                                             pathways
2      MOCOS                                Molybdenum cofactor sulfurase;MOCOS;PTN002494397;orthologs  Homo sapiens            NaN                                                                                                                                                                                                                                                                                                                                                                                                  NaN
5    CFAP119                 Cilia- and flagella-associated protein 119;CFAP119;PTN002523846;orthologs  Homo sapiens            NaN                                                                                                                                                                                                                                                                                                                                                                                                  NaN
7     TRAJ10                                           Possible J 10 gene (Fragment);TRAJ10;;orthologs  Homo sapiens            NaN                                                                                                                                                                                                                                                                                                                                                                                                  NaN
10    ZNF688                                     Zinc finger protein 688;ZNF688;PTN002555844;orthologs  Homo sapiens            NaN                                                                                                                                                                                                                                                                                                                                                                                                  NaN
11  FAM90A2P                                 Putative protein FAM90A2P;FAM90A2P;PTN002496904;orthologs  Homo sapiens            NaN                                                                                                                                                                                                                                                                                                                                                                                                  NaN
12      PDHX     Pyruvate dehydrogenase protein X component, mitochondrial;PDHX;PTN002508708;orthologs  Homo sapiens            NaN                                                                                                                                                                                                                                                                                                                                                                                                  NaN
18     NPTX2                                         Neuronal pentraxin-2;NPTX2;PTN002499355;orthologs  Homo sapiens            NaN                                                                                                                                                                                                                                                                                                                                                                                                  NaN
19     MROH8                                                            Protein MROH8;MROH8;;orthologs  Homo sapiens            NaN                                                                                                                                                                                                                                                                                                                                                                                                  NaN
24    HOXC13                                    Homeobox protein Hox-C13;HOXC13;PTN002518624;orthologs  Homo sapiens            NaN                                                                                                                                                                                                                                                                                                                                                                                                  NaN
25     TSPY9                          Testis-specific Y-encoded protein 9;TSPY9;PTN008331607;orthologs  Homo sapiens            NaN                                                                                                                                                                                                                                                                                                                                                                                                  NaN
26     CTDP1    RNA polymerase II subunit A C-terminal domain phosphatase;CTDP1;PTN002507850;orthologs  Homo sapiens            NaN                                                                                                                                                                                                                                                       Transcription regulation by bZIP transcription factor->Transcription factor IIF;;General transcription regulation->Transcription factor IIF;;;
27    TMEM78                                                Transmembrane protein 78;TMEM78;;orthologs  Homo sapiens            NaN                                                                                                                                                                                                                                                                                                                                                                                                  NaN
28      MEA1                                       Male-enhanced antigen 1;MEA1;PTN002497729;orthologs  Homo sapiens            NaN                                                                                                                                                                                                                                                                                                                                                                                                  NaN
30     TTC13                          Tetratricopeptide repeat protein 13;TTC13;PTN002549443;orthologs  Homo sapiens            NaN                                                                                                                                                                                                                                                                                                                                                                                                  NaN
31     GVQW3                                                Protein GVQW3;GVQW3;PTN002281887;orthologs  Homo sapiens            NaN                                                                                                                                                                                                                                                                                                                                                                                                  NaN
34      NEK1                          Serine_threonine-protein kinase Nek1;NEK1;PTN002519603;orthologs  Homo sapiens            NaN                                                                                                                                                                                                                                                                                                                                                                                                  NaN
35      ORM1                                   Alpha-1-acid glycoprotein 1;ORM1;PTN002485428;orthologs  Homo sapiens            NaN                                                                                                                                                                                                                                                                                                                                                                                                  NaN
42   SLC45A1                      Proton-associated sugar transporter A;SLC45A1;PTN002500289;orthologs  Homo sapiens            NaN                                                                                                                                                                                                                                                                                                                                                                                                  NaN
45    COL6A1                                  Collagen alpha-1(VI) chain;COL6A1;PTN002544441;orthologs  Homo sapiens            NaN                                                                                                                                                                                                                                                            Inflammation mediated by chemokine and cytokine signaling pathway->ExtraCellular matrix protein;;Integrin signalling pathway->Collagen;;;
46    NPIPA2   Nuclear pore complex-interacting protein family member A2;NPIPA2;PTN002496011;orthologs  Homo sapiens            NaN                                                                                                                                                                                                                                                                                                                                                                                                  NaN
51    BPIFB6                       BPI fold-containing family B member 6;BPIFB6;PTN002471176;orthologs  Homo sapiens            NaN                                                                                                                                                                                                                                                                                                                                                                                                  NaN
54    GOLT1A                             Vesicle transport protein GOT1A;GOLT1A;PTN002502093;orthologs  Homo sapiens            NaN                                                                                                                                                                                                                                                                                                                                                                                                  NaN
55    ODF3L2                  Outer dense fiber protein 3-like protein 2;ODF3L2;PTN002502444;orthologs  Homo sapiens            NaN                                                                                                                                                                                                                                                                                                                                                                                                  NaN
57     OR6C1                                       Olfactory receptor 6C1;OR6C1;PTN002522925;orthologs  Homo sapiens            NaN                                                                                                                                                                                                                                                                                                                                                                                                  NaN
58     SKIC2                                Superkiller complex protein 2;SKIC2;PTN002486318;orthologs  Homo sapiens            NaN                                                                                                                                                                                                                                                                                                                                                                                                  NaN
61     ACTG2                           Actin, gamma-enteric smooth muscle;ACTG2;PTN002485038;orthologs  Homo sapiens            NaN  Cadherin signaling pathway->Filamentous F-actin;;Alzheimer disease-presenilin pathway->actin;;Inflammation mediated by chemokine and cytokine signaling pathway->F-actin;;Wnt signaling pathway->NFAT Target Genes;;Nicotinic acetylcholine receptor signaling pathway->Actin;;Huntington disease->Actin;;Integrin signalling pathway->Actin;;Cytoskeletal regulation by Rho GTPase->Actin;;;;;;;;;
63    EFEMP1  EGF-containing fibulin-like extracellular matrix protein 1;EFEMP1;PTN002542817;orthologs  Homo sapiens            NaN                                                                                                                                                                                                                                                                                                                                                                                                  NaN
65     FBLN2                                                    Fibulin-2;FBLN2;PTN002552695;orthologs  Homo sapiens            NaN                                                                                                                                                                                                                                                                                                                                                                                                  NaN
66   C8ORF17                                                         Protein MOST-1;C8orf17;;orthologs  Homo sapiens            NaN                                                                                                                                                                                                                                                                                                                                                                                                  NaN
67     IQCF5                              IQ domain-containing protein F5;IQCF5;PTN002502539;orthologs  Homo sapiens            NaN                                                                                                                                                                                                                                                                                                                                                                                                  NaN

In [86]:
print(
    "Empty GO annotations:",
    panther_df["go_annotations"].isna().sum()
)

print(
    "Blank GO annotations:",
    (panther_df["go_annotations"].fillna("").str.strip() == "").sum()
)

Empty GO annotations: 8146
Blank GO annotations: 8146

In [87]:
go_pattern = panther_df["go_annotations"].fillna("").str.contains(
    r"GO:\d+",
    regex=True
)

print("Rows containing GO ID:", go_pattern.sum())
print("Rows without GO ID:", (~go_pattern).sum())

Rows containing GO ID: 12434
Rows without GO ID: 8146

In [89]:
go_rows = panther_df[
    panther_df["go_annotations"].fillna("").str.contains(
        r"GO:\d+", regex=True
    )
].copy()

print("GO-containing rows:", len(go_rows))
print("Unique genes:", go_rows["gene_name"].nunique())

print("\nGenes occurring more than once:")
print(
    go_rows["gene_name"]
    .value_counts()
    .loc[lambda x: x > 1]
    .head(30)
)

GO-containing rows: 12434
Unique genes: 12407

Genes occurring more than once:
gene_name
UNASSIGNED    22
KIR2DL1        3
TMSB15B        2
OR2A42         2
OR2A25         2
ARHGEF18       2
Name: count, dtype: int64

In [90]:
go_df_combined

,gene_name,go_id,biological_function
0,A1BG,GO:0002764,immune response-regulating signaling pathway
1,A3GALT2,GO:0030258; GO:0070085,glycosylation; lipid modification
2,A4GALT,GO:0006688,glycosphingolipid biosynthetic process
3,A4GNT,GO:0006493; GO:0006688,glycosphingolipid biosynthetic process; protei...
4,AAAS,GO:0006913,nucleocytoplasmic transport
...,...,...,...
12402,ZWILCH,GO:0007094; GO:0034501,mitotic spindle assembly checkpoint signaling;...
12403,ZXDA,GO:0006357,regulation of transcription by RNA polymerase II
12404,ZXDB,GO:0006357,regulation of transcription by RNA polymerase II
12405,ZXDC,GO:0006357,regulation of transcription by RNA polymerase II
12406,ZYX,GO:0007179; GO:0007229,integrin-mediated signaling pathway; transform...

In [91]:
function_counts = (
    go_df.groupby("biological_function")["gene_name"]
    .nunique()
    .reset_index(name="gene_count")
    .sort_values("gene_count", ascending=False)
    .reset_index(drop=True)
)

print(function_counts.head(30))

                                  biological_function  gene_count
0    regulation of transcription by RNA polymerase II        1254
1        G protein-coupled receptor signaling pathway         240
2   positive regulation of transcription by RNA po...         216
3                                cell differentiation         198
4   negative regulation of transcription by RNA po...         191
5                                 signal transduction         179
6                              protein ubiquitination         176
7                                     immune response         172
8           regulation of DNA-templated transcription         161
9                                       cell adhesion         139
10  detection of chemical stimulus involved in sen...         139
11                  intracellular signal transduction         137
12                            protein phosphorylation         135
13            cell surface receptor signaling pathway         128
14                    intracellular protein transport         128
15  transmembrane receptor protein tyrosine kinase...         124
16                                        proteolysis         121
17                             innate immune response         119
18                                     cell migration         116
19                  extracellular matrix organization         109
20                   peptidyl-amino acid modification         109
21      ubiquitin-dependent protein catabolic process         108
22                cytokine-mediated signaling pathway         106
23  proteasome-mediated ubiquitin-dependent protei...         105
24  adenylate cyclase-activating G protein-coupled...         103
25            immunoglobulin mediated immune response         101
26                                    protein folding          98
27  production of molecular mediator of immune res...          97
28                                    cilium assembly          97
29                      regulation of gene expression          96

In [92]:
function_counts

                                    biological_function  gene_count
0      regulation of transcription by RNA polymerase II        1254
1          G protein-coupled receptor signaling pathway         240
2     positive regulation of transcription by RNA po...         216
3                                  cell differentiation         198
4     negative regulation of transcription by RNA po...         191
...                                                 ...         ...
1794                                V(D)J recombination           1
1795                       GPI anchor metabolic process           1
1796                     tetrapyrrole metabolic process           1
1797                                  tissue remodeling           1
1798                                lipid translocation           1

[1799 rows x 2 columns]

In [93]:
go_df_combined = (
    go_df[
        (go_df["gene_name"].notna()) &
        (go_df["gene_name"].str.upper() != "UNASSIGNED")
    ]
    .groupby("gene_name", as_index=False)
    .agg({
        "go_id": lambda x: "; ".join(sorted(set(x))),
        "biological_function": lambda x: "; ".join(sorted(set(x)))
    })
    .reset_index(drop=True)
)

In [94]:
go_df_combined.to_csv(
    "go_gene_functions.tsv",
    sep="\t",
    index=False
)